### ISSUE TITLE
Use compressed bitmap to track ID usage

### ISSUE THREAD

**Issue by kingjon3377** [kingjon3377/strategicprimer-viewer#53]
Instead of using a Java `BitMap`, or worse a `HashSet<Integer>`, we should use a compressed bit-map (using e.g. [JavaEWAH](https://github.com/lemire/javaewah)) to track which ID numbers have been used. Based on that library's documentation, this should improve both performance and memory usage. I hate to add yet another dependency, but this looks like a clear enough win to be worth it.

**Comment by kingjon3377** [comment]
Unfortunately, both JavaEWAH and RoaringBitmap have one fatal flaw preventing me from using either of them: neither provides a way to efficiently get the first unused bit. (I found a bug report asking for this to be implemented, then couldn't find it again to link here.)

**Comment by kingjon3377** [comment]
A relevant issue is RoaringBitmap/RoaringBitmap#287.

**Comment by incaseoftrouble** [comment]
Hi, https://github.com/RoaringBitmap/RoaringBitmap/issues/282 should also be relevant (they are sort of the same issue). I'll maybe get around working on these two things this week.

You could also have a look at https://github.com/brettwooldridge/SparseBitSet in the meantime. This supports querying for absent bits (`nextClearBit(int)`).

Finally (shameless self-advertisement) you could delegate to my library https://github.com/incaseoftrouble/naturals-util which basically is an abstraction for several bitmap implementations, trying to mimic a `Set<Integer>` with some additional features. For a roaring bitmaps backend, I currently emulate the next clear bit with a binary search. Disclaimer: Currently, there is a dependency on fastutil, which blows up the distribution size quite a bit (~20mb). Also its Java 8.

**Comment by kingjon3377** [comment]
Thanks for the pointers. I think that RoaringBitmap/RoaringBitmap#282 was indeed the issue I had originally found (I see I'm "subscribed" to it already). A 20-meg dependency is indeed a deal-breaker for me (at 34 megs my app is already over-bloated), but the SparseBitSet looks like it will serve my needs fairly well. Thanks again!
